---
sidebar: sidebar 
permalink: tanzu/vtwn-solution-overview.html 
keywords: VMware Tanzu, Tanzu, DevOps, Netapp, Trident, Trident Protect 
summary: 'Questo documento di riferimento fornisce la convalida della distribuzione di diverse tipologie di soluzioni VMware Tanzu Kubernetes, distribuite come Tanzu Kubernetes Grid (TKG), Tanzu Kubernetes Grid Service (TKGS) o Tanzu Kubernetes Grid Integrated (TKGI) in diversi ambienti di data center, come convalidato da NetApp.' 
---
= NVA-1166: VMware Tanzu con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Alan Cowles e Nikhil M Kulkarni, NetApp

[role="lead"]
Questo documento di riferimento fornisce la convalida della distribuzione di diverse tipologie di soluzioni VMware Tanzu Kubernetes, distribuite come Tanzu Kubernetes Grid (TKG), Tanzu Kubernetes Grid Service (TKGS) o Tanzu Kubernetes Grid Integrated (TKGI) in diversi ambienti di data center, come convalidato da NetApp.  Descrive inoltre l'integrazione dello storage con i sistemi di storage NetApp e l'orchestratore di storage Trident per la gestione dello storage persistente e Trident Protect per il backup e la clonazione delle applicazioni con stato che utilizzano tale storage persistente.  Infine, il documento fornisce dimostrazioni video delle integrazioni e delle convalide della soluzione.



== Casi d'uso

La soluzione VMware Tanzu con NetApp è progettata per offrire un valore eccezionale ai clienti con i seguenti casi d'uso:

* Le offerte VMware Tanzu Kubernetes Grid sono facili da implementare e gestire, distribuite su VMware vSphere e integrate con i sistemi di storage NetApp .
* La potenza combinata dei container aziendali e dei carichi di lavoro virtualizzati con le offerte VMware Tanzu Kubernetes Grid.
* Configurazione e casi d'uso reali che evidenziano le funzionalità di VMware Tanzu quando utilizzato con lo storage NetApp e la suite di prodotti NetApp Trident .
* Protezione o migrazione coerente con l'applicazione di carichi di lavoro containerizzati distribuiti su cluster VMware Tanzu Kubernetes Grid i cui dati risiedono su sistemi di storage NetApp che utilizzano Trident Protect.




== Valore aziendale

Le aziende stanno adottando sempre più pratiche DevOps per creare nuovi prodotti, abbreviare i cicli di rilascio e aggiungere rapidamente nuove funzionalità.  Grazie alla loro innata natura agile, i container e i microservizi svolgono un ruolo cruciale nel supportare le pratiche DevOps.  Tuttavia, mettere in pratica DevOps su scala produttiva in un ambiente aziendale presenta le sue sfide e impone determinati requisiti all'infrastruttura sottostante, come i seguenti:

* Elevata disponibilità a tutti i livelli dello stack
* Facilità delle procedure di distribuzione
* Operazioni e aggiornamenti non dirompenti
* Infrastruttura programmabile e basata su API per tenere il passo con l'agilità dei microservizi
* Multitenancy con garanzie di prestazione
* Capacità di eseguire carichi di lavoro virtualizzati e containerizzati simultaneamente
* Capacità di scalare l'infrastruttura in modo indipendente in base alle richieste del carico di lavoro
* Possibilità di distribuzione in un modello cloud ibrido con container in esecuzione sia nei data center locali che nel cloud.


VMware Tanzu con NetApp riconosce queste sfide e presenta una soluzione che aiuta a risolvere ogni problema distribuendo le offerte VMware Tanzu Kubernetes nell'ambiente cloud ibrido scelto dal cliente.



== Panoramica della tecnologia

La soluzione VMware Tanzu con NetApp è composta dai seguenti componenti principali:



=== Piattaforme VMware Tanzu Kubernetes

VMware Tanzu è disponibile in una varietà di versioni che il team di ingegneria delle soluzioni di NetApp ha convalidato nei nostri laboratori.  Ogni versione di Tanzu si integra con successo con il portfolio di storage NetApp e ciascuna può contribuire a soddisfare determinate esigenze infrastrutturali.  I seguenti punti salienti descrivono le caratteristiche e le offerte di ciascuna versione di Tanzu descritta in questo documento.

*Griglia VMware Tanzu Kubernetes (TKG)*

* Ambiente Kubernetes upstream standard distribuito in un ambiente VMware vSphere.
* Precedentemente noto come Essential PKS (dall'acquisizione di Heptio, febbraio 2019).
* TKG viene distribuito con un'istanza di cluster di gestione separata per il supporto su vSphere 6.7U3 e versioni successive.
* Le distribuzioni TKG possono essere distribuite anche nel cloud con AWS o Azure.
* Consente l'utilizzo di nodi worker Windows o Linux (Ubuntu/Photon).
* Per il piano di controllo è possibile utilizzare NSX-T, HA Proxy, reti AVI o bilanciatori di carico.
* TKG supporta MetalLB per il piano dati/applicazione.
* È possibile utilizzare vSphere CSI e CSI di terze parti come NetApp Trident.


*Servizio griglia VMware Tanzu Kubernetes (TKGS)*

* Ambiente Kubernetes upstream standard distribuito in un ambiente VMware vSphere.
* Precedentemente noto come Essential PKS (dall'acquisizione di Heptio, febbraio 2019).
* TKGS distribuito con cluster di supervisore e cluster di carichi di lavoro solo su vSphere 7.0U1 e versioni successive.
* Consente l'utilizzo di nodi worker Windows o Linux (Ubuntu/Photon).
* Per il piano di controllo è possibile utilizzare NSX-T, HA Proxy, reti AVI o bilanciatori di carico.
* TKGS supporta MetalLB per il piano dati/applicazioni.
* È possibile utilizzare vSphere CSI e CSI di terze parti come NetApp Trident.
* Fornisce supporto per vSphere Pods con Tanzu, consentendo l'esecuzione dei pod direttamente sugli host ESXi abilitati nell'ambiente.


*VMWare Tanzu Kubernetes Grid Integrated (TKGI)*

* Precedentemente noto come Enterprise PKS (dall'acquisizione di Heptio, febbraio 2019).
* È possibile utilizzare NSX-T, HA Proxy o Avi.  Puoi anche fornire il tuo bilanciatore di carico.
* Supportato da vSphere 6.7U3 in poi, nonché da AWS, Azure e GCP.
* Configurazione tramite procedura guidata per semplificare l'implementazione.
* Esegue Tanzu in VM immutabili controllate gestite da BOSH.
* È possibile utilizzare vSphere CSI e CSI di terze parti come NetApp Trident (si applicano alcune condizioni).


*vSphere con Tanzu (vSphere Pod)*

* I pod nativi di vSphere vengono eseguiti in uno strato sottile basato su fotoni con hardware virtuale prescritto per un isolamento completo.
* Richiede NSX-T, ma ciò consente il supporto di funzionalità aggiuntive, come un registro di immagini Harbor.
* Distribuito e gestito in vSphere 7.0U1 e versioni successive utilizzando un cluster Supervisor virtuale come TKGS.  Esegue i pod direttamente sui nodi ESXi.
* Completamente integrato con vSphere, massima visibilità e controllo tramite l'amministrazione vSphere.
* Pod isolati basati su CRX per il massimo livello di sicurezza.
* Supporta solo vSphere CSI per l'archiviazione persistente.  Non sono supportati orchestratori di archiviazione di terze parti.




=== Sistemi di archiviazione NetApp

NetApp dispone di diversi sistemi di storage ideali per data center aziendali e implementazioni cloud ibride.  Il portfolio NetApp include i sistemi di storage NetApp ONTAP, NetApp Element e NetApp e-Series, tutti in grado di fornire storage persistente per applicazioni containerizzate.

Per maggiori informazioni, visita il sito web NetApp https://www.netapp.com["Qui"] .



=== Integrazioni di storage NetApp

Trident è un orchestratore di storage open source e completamente supportato per container e distribuzioni Kubernetes, tra cui VMware Tanzu.

Per maggiori informazioni, visita il sito web Trident https://docs.netapp.com/us-en/trident/index.html["Qui"] .



== Matrice di supporto attuale per le versioni convalidate

|===


| Tecnologia | Scopo | Versione del software 


| NetApp ONTAP | Magazzinaggio | 9.9.1 


| NetApp Trident | Orchestrazione dell'archiviazione | 22.04.0 


| VMware Tanzu Kubernetes Grid | Orchestrazione dei contenitori | 1.4+ 


.2+| Servizio di griglia VMware Tanzu Kubernetes .2+| Orchestrazione dei contenitori | 0.0.15 [Spazi dei nomi vSphere] 


| 1.22.6 [Cluster di supervisione Kubernetes] 


| VMware Tanzu Kubernetes Grid integrato | Orchestrazione dei contenitori | 1.13.3 


| VMware vSphere | Virtualizzazione del data center | 7.0U3 


| Data center VMware NSX-T | Rete e sicurezza | 3.1.3 


| Bilanciatore di carico avanzato VMware NSX | Bilanciatore del carico | 20.1.3 
|===