---
sidebar: sidebar 
permalink: anthos/anthos-trident-ontap-iscsi.html 
summary: 'Per abilitare l"integrazione Trident con il sistema di storage NetApp ONTAP , è necessario creare un backend che consenta la comunicazione con il sistema di storage.' 
keywords: Trident, Trident, ONTAP, AFF, FAS, iSCSI 
---
= Configurazione iSCSI NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per abilitare l'integrazione Trident con il sistema di storage NetApp ONTAP , è necessario creare un backend che consenta la comunicazione con il sistema di storage.

. Sono disponibili file di backend di esempio nell'archivio di installazione scaricato in `sample-input` gerarchia delle cartelle.  Per i sistemi NetApp ONTAP che servono iSCSI, copiare il `backend-ontap-san.json` file nella directory di lavoro e modificarlo.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/backends-samples/ontap-san/backend-ontap-san.json ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi backend-ontap-san.json
----
. Modificare i valori managementLIF, dataLIF, svm, username e password in questo file.
+
[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "172.21.224.201",
  "dataLIF": "10.61.181.240",
  "svm": "trident_svm",
  "username": "admin",
  "password": "password"
}
----
. Con questo file backend al suo posto, esegui il seguente comando per creare il tuo primo backend.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-san.json
+------------------------+----------------+--------------------------------------+--------+---------+
|          NAME          | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------------------+----------------+--------------------------------------+--------+---------+
| ontapsan_10.61.181.241 | ontap-san      | 6788533c-7fea-4a35-b797-fb9bb3322b91 | online |       0 |
+------------------------+----------------+--------------------------------------+--------+---------+
----
. Dopo aver creato il backend, è necessario creare una classe di archiviazione.  Proprio come per il backend, nella cartella sample-inputs è disponibile un file di classe di archiviazione di esempio che può essere modificato per l'ambiente.  Copialo nella directory di lavoro e apporta le modifiche necessarie per riflettere il backend creato.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi storage-class-basic.yaml
----
. L'unica modifica che deve essere apportata a questo file è definire il `backendType` valore al nome del driver di archiviazione dal backend appena creato.  Si noti anche il valore del campo nome, a cui si dovrà fare riferimento in un passaggio successivo.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
----
+

NOTE: C'è un campo facoltativo chiamato `fsType` che è definito in questo file.  Nei backend iSCSI, questo valore può essere impostato su un tipo di file system Linux specifico (XFS, ext4 e così via) oppure può essere eliminato per consentire al sistema operativo del nodo worker di decidere quale file system utilizzare.

. Esegui il `kubectl` comando per creare la classe di archiviazione.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Dopo aver creato la classe di archiviazione, è necessario creare la prima richiesta di volume persistente (PVC).  C'è un campione `pvc-basic.yaml` file che può essere utilizzato per eseguire questa azione, anch'esso presente in sample-inputs.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi pvc-basic.yaml
----
. L'unica modifica che deve essere apportata a questo file è assicurarsi che il `storageClassName` il campo corrisponde a quello appena creato.  La definizione PVC può essere ulteriormente personalizzata in base alle esigenze del carico di lavoro da fornire.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Creare il PVC emettendo il `kubectl` comando.  La creazione può richiedere del tempo a seconda delle dimensioni del volume di supporto creato, quindi è possibile osservare il processo mentre viene completato.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-7ceac1ba-0189-43c7-8f98-094719f7956c   1Gi        RWO            basic-csi      3s
----

