---
sidebar: sidebar 
permalink: anthos/anthos-advanced-overview.html 
keywords: Advanced Configuration, Load Balancers 
summary: Questa sezione è dedicata alle personalizzazioni che gli utenti reali potrebbero dover eseguire durante la distribuzione di questa soluzione in produzione, ad esempio la distribuzione di istanze di bilanciamento del carico personalizzate. 
---
= Opzioni di configurazione avanzate
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In genere, la soluzione più semplice da implementare è la migliore, ma in alcuni casi sono necessarie personalizzazioni avanzate per soddisfare i requisiti o le specifiche di un'applicazione specifica o dell'ambiente in cui la soluzione viene implementata.  A tal fine, la soluzione Red Hat OpenShift con NetApp consente le seguenti personalizzazioni per soddisfare queste esigenze.


NOTE: In questa sezione abbiamo documentato alcune opzioni di configurazione avanzate, come l'utilizzo di bilanciatori di carico di terze parti o la creazione di un registro privato per l'hosting di immagini di container personalizzate, entrambi prerequisiti per l'installazione di NetApp Trident Protect.

Le pagine seguenti contengono informazioni aggiuntive sulle opzioni di configurazione avanzate convalidate nella soluzione Red Hat OpenShift con NetApp :
