---
sidebar: sidebar 
permalink: videos/tanzu-videos.html 
keywords: video, demonstration, deployment, VMware Tanzu with NetApp, NetApp, Tanzu 
summary: Questa pagina contiene link a video che dimostrano alcune delle funzionalità descritte nel presente documento. 
---
= Guarda i video su VMware Tanzu con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esplora l'integrazione di VMware Tanzu con NetApp attraverso una serie di video che dimostrano le funzionalità chiave, come il provisioning di storage persistente, la clonazione delle applicazioni e la protezione dei dati utilizzando Trident.


NOTE: Queste demo sono state registrate come anteprima tecnica utilizzando la versione 1.3.1 di TKG e la versione 21.12 di Trident Protect.  Per le versioni supportate ufficialmente, consultare la matrice di supporto.



== Provisioning di storage persistente

.Utilizzare Trident per fornire storage persistente in VMware Tanzu - VMware Tanzu con NetApp
video::8db3092b-3468-4754-b2d7-b01200fbb38d[panopto,width=360]


== Clonazione delle applicazioni e protezione dei dati

.Utilizzare Trident Protect per clonare le applicazioni in VMWare Tanzu - VMware Tanzu con NetApp
video::01aff358-a0a2-4c4f-9062-b01200fb9abd[panopto,width=360]