---
sidebar: sidebar 
permalink: openshift/os-adv-mgmt-deployment-prereq.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, ONTAP, Trident, Red Hat OpenShift, Advanced Cluster Management, Advanced Cluster Management for Kubernetes 
summary: Gestione avanzata dei cluster per Kubernetes su Red Hat OpenShift con NetApp 
---
= Distribuisci Advanced Cluster Management per Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione riguarda la gestione avanzata dei cluster per Kubernetes su Red Hat OpenShift con NetApp.



[[prerequisites]]
== Prerequisiti

. Un cluster Red Hat OpenShift (versione superiore alla 4.5) per il cluster hub
. Cluster Red Hat OpenShift (superiori alla versione 4.4.3) per cluster gestiti
. Accesso Cluster-admin al cluster Red Hat OpenShift
. Un abbonamento Red Hat per Advanced Cluster Management per Kubernetes


Advanced Cluster Management è un componente aggiuntivo per il OpenShift cluster, quindi ci sono determinati requisiti e limitazioni sulle risorse hardware in base alle funzionalità utilizzate tra l'hub e i cluster gestiti. Devi tenere conto di questi aspetti quando dimensioni i cluster. Vedi link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html-single/install/index#network-configuration["Requisiti di configurazione di rete"^] per maggiori dettagli.

Facoltativamente, se il cluster dispone di nodi dedicati per l'hosting dei componenti dell'infrastruttura e vuoi installare le risorse di Advanced Cluster Management solo su quei nodi, devi aggiungere tolleranze e selettori a quei nodi di conseguenza. Per ulteriori dettagli, vedi link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/install/installing#installing-on-infra-node["Installazione sui nodi dell'infrastruttura"^].
