---
sidebar: sidebar 
permalink: openshift/os-trident-ontap-nfs.html 
keywords: Trident, Trident, ONTAP, AFF, FAS, NFS 
summary: 'Per abilitare l"integrazione Trident con il sistema di storage NetApp ONTAP è necessario creare un backend che consenta la comunicazione con il sistema di storage.' 
---
= Configurazione NFS NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per abilitare l'integrazione Trident con il sistema di storage NetApp ONTAP , è necessario creare un backend che consenta la comunicazione con il sistema di storage.

. Sono disponibili file di backend di esempio nell'archivio di installazione scaricato in `sample-input` gerarchia delle cartelle.  Per i sistemi NetApp ONTAP che servono NFS, copiare il `backend-ontap-nas.json` file nella directory di lavoro e modificarlo.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/backends-samples/ontap-nas/backend-ontap-nas.json ./
[netapp-user@rhel7 trident-installer]$ vi backend-ontap-nas.json
----
. Modificare i valori backendName, managementLIF, dataLIF, svm, username e password in questo file.
+
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "ontap-nas+10.61.181.221",
    "managementLIF": "172.21.224.201",
    "dataLIF": "10.61.181.221",
    "svm": "trident_svm",
    "username": "cluster-admin",
    "password": "password"
}
----
+

NOTE: Per una facile identificazione, è consigliabile definire il valore backendName personalizzato come una combinazione di storageDriverName e dataLIF che gestisce NFS.

. Con questo file backend al suo posto, esegui il seguente comando per creare il tuo primo backend.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-nas.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| ontap-nas+10.61.181.221 | ontap-nas      | be7a619d-c81d-445c-b80c-5c87a73c5b1e | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. Dopo aver creato il backend, è necessario creare una classe di archiviazione.  Proprio come per il backend, nella cartella sample-inputs è disponibile un file di classe di archiviazione di esempio che può essere modificato per l'ambiente.  Copialo nella directory di lavoro e apporta le modifiche necessarie per riflettere il backend creato.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[netapp-user@rhel7 trident-installer]$ vi storage-class-basic.yaml
----
. L'unica modifica che deve essere apportata a questo file è definire il `backendType` valore al nome del driver di archiviazione dal backend appena creato.  Si noti anche il valore del campo nome, a cui si dovrà fare riferimento in un passaggio successivo.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
----
+

NOTE: C'è un campo facoltativo chiamato `fsType` che è definito in questo file.  Questa riga può essere eliminata nei backend NFS.

. Esegui il `oc` comando per creare la classe di archiviazione.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Dopo aver creato la classe di archiviazione, è necessario creare la prima richiesta di volume persistente (PVC).  C'è un campione `pvc-basic.yaml` file che può essere utilizzato per eseguire questa azione, anch'esso presente in sample-inputs.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[netapp-user@rhel7 trident-installer]$ vi pvc-basic.yaml
----
. L'unica modifica che deve essere apportata a questo file è assicurarsi che il `storageClassName` il campo corrisponde a quello appena creato.  La definizione PVC può essere ulteriormente personalizzata in base alle esigenze del carico di lavoro da fornire.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Creare il PVC emettendo il `oc` comando.  La creazione può richiedere del tempo a seconda delle dimensioni del volume di supporto creato, quindi è possibile osservare il processo mentre viene completato.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[netapp-user@rhel7 trident-installer]$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-b4370d37-0fa4-4c17-bd86-94f96c94b42d   1Gi        RWO            basic-csi      7s
----

